name: Build and Upload JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Jar with Gradle
        run: ./gradlew shadowJar


      - name: Upload JAR file
        uses: actions/upload-artifact@v4.4.0
        with:
          name: my-app
          path: build/libs/*.jar